# Generated by Django 5.0.3 on 2024-04-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0029_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookflight',
            old_name='username_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='bookhotel',
            old_name='username_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='bookpackage',
            old_name='username_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='flights',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
